spring:
  # RabbitMQ
  rabbitmq:
    username: guest
    password: guest
    port: 5672
    # 开启 publisher-confirms
    publisher-confirms: true
    # 开启 publisher-returns, 路由不到指定队列时触发回调.
    publisher-returns: true
    # 开启手动确认、设置未确认消息上限
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 100
    # 设置 mandatory 属性，当发送不到对应的交换器的时候，就返回给发送方, false表示丢弃
    template:
      mandatory: true

  # mysql
  datasource:
    url: jdbc:mysql://localhost:3306/rabbitMQ-Email?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

