# RabbitMQ
spring:
  rabbitmq:
    username: guest
    password: guest
    port: 5672
    # 开启 publisher-confirms
    publisher-confirms: true
    # 开启 publisher-returns, 路由不到指定队列时触发回调.
    publisher-returns: true
    # 开启手动确认、设置未确认消息上限
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 100