spring:
  # RabbitMQ
  rabbitmq:
    username: guest
    password: guest
    port: 5672
    # 开启 publisher-confirms
    publisher-confirms: true
    # 开启 publisher-returns, 路由不到指定队列时触发回调.
    publisher-returns: true
    # 开启手动确认、设置未确认消息上限
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 100

  # mysql
  datasource:
    url: jdbc:mysql://localhost:3306/rabbitMQ-Email?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

